apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim-name
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi